# Site Settings
site_name: Sonic Adventure Stage Tools for Blender
site_description: Usage manual for the Sonic Adventure Stage Tools Blender addon.
site_author: ItsEasyActually and Contributors

repo_url: https://github.com/ItsEasyActually/SonicAdventureStageTools/
repo_name: SonicAdventureStageTools

docs_dir: docs

plugins: 
  - search

extra_css: 
  - _sitedev/stylesheets/light.css
  - _sitedev/stylesheets/dark.css

extra_javascript: 
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - sitedev/javascript/tablesort.js

# Theme Settings
theme:
  name: material
  custom_dir: docs/_sitedev/overrides
  favicon: _sitedev/assets/svg/favicon.svg
  logo: _sitedev/assets/svg/icon.svg
  icon:
    edit: material/pencil
    view: material/eye
    annotation: material/help-circle
  font:
    text: Sora
    code: Noto Sans Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: sastdark
      toggle:
        icon: material/brightness-5
        name: Switch to Light Theme
    - media: "(prefers-color-scheme: light)"
      scheme: sastlight
      toggle:
        icon: material/brightness-2
        name: Switch to Dark Theme


# Navigation
nav:
  - Home: index.md
  - Installation: 
    - installation/index.md
  - Features:
    - features/index.md
  - Guides:
    - guides/index.md
  - Contributing:
    - contributing/index.md
    - Contribution Guidelines:
      - contributing/addon-contributing.md
      - contributing/docs-contributing.md