# Site Settings
site_name: Sonic Adventure Stage Tools for Blender
site_description: Usage manual for the Sonic Adventure Stage Tools Blender addon.
site_author: ItsEasyActually and Contributors

repo_url: https://github.com/ItsEasyActually/SonicAdventureStageTools/
repo_name: SonicAdventureStageTools

docs_dir: docs

plugins: 
  - search

extra_css: 
  - _sitedev/stylesheets/light.css
  - _sitedev/stylesheets/dark.css

extra_javascript: 
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - sitedev/javascript/tablesort.js

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Theme Settings
theme:
  name: material
  favicon: _sitedev/assets/svg/favicon.svg
  logo: _sitedev/assets/svg/icon.svg
  icon:
    edit: material/pencil
    view: material/eye
    annotation: material/plus-circle-outline
  font:
    text: Comfortaa
    code: Noto Sans Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: sastdark
      toggle:
        icon: material/brightness-5
        name: Switch to Light Theme
    - media: "(prefers-color-scheme: light)"
      scheme: sastlight
      toggle:
        icon: material/brightness-2
        name: Switch to Dark Theme


# Navigation
nav:
  - Home: index.md
  - Installation: 
    - installation/index.md
  - Manual:
    - manual/index.md
    - Editor Panel:
      - Scene Settings: 
        - manual/scene/index.md
        - manual/scene/settings.md
        - manual/scene/object-list.md
      - Utilities:
        - manual/utilities/index.md
      - Editor Objects:
        - manual/objects/index.md
        - CAM Objects: 
          - manual/objects/sa1cam-objects.md
          - manual/objects/sa2cam-objects.md
          - manual/objects/sa2campoint-objects.md
        - SET Objects: manual/objects/set-objects.md
      - Addon Preferences:
        - manual/preferences/index.md
  - Guides:
    - guides/index.md
  - Contributing:
    - contributing/index.md
    - Contribution Guidelines:
      - contributing/addon-contributing.md
      - contributing/docs-contributing.md